### ISSUE TITLE
Update the links

### ISSUE THREAD

**Issue by Oredna** [IdleEndeavor/booksearch#2]
### Links that need to be removed, because google doesn't index them:
- libgen.fun
- libgen.rs/fiction
- epublibre.org/
- freefullpdf.com/*
- snewd.com/*
- ikindlebooks.com/*

### Links that need to be changed:
- ibookpile.net to ibookpile.in

### Links to be added:
- b-ok.cc/*
- pdfdrive.com/*
- repec.org/*
- snti.ru/*
- magazinelib.com/*
- avxhome.se/*
- freebookspot.club/*
- librs.net/*
- booksc.org/*
- ebookjunkie.com/*
- scribd.com/*
- onlineprogrammingbooks.com/*
- perlego.com/*
- bookboon.com/*
- broward.org/*
- ebookee.com/*
- free-ebooks.net/*
- smashwords.com/*
- oll.libertyfund.org/*
- 2020ok.com/*
- audiobookbay.ch/*
- ebb.la/*
- textbooknova.com/*
- pdfchm.net/*
- ebook3000.com/*
- bookfi.net/*
- openlibrary.org/*
- scienceopen.com/*
- pdfbooksworld.com/*
- feedbooks.com/*
- doaj.org/*
- plos.org/*
- dlc.dlib.indiana.edu/*
- paperity.org/*
- dblp.org/*
- zenodo.org/*
- the-eye.eu/*
- forcoder.su/*
- forum.mobilism.org/*
- filepursuit.com/*

**Comment by IdleEndeavor** [comment]
Thank you so much for these links! I'll be going through all of them and making changes by the end of this week.
