### ISSUE TITLE
Ravebooksearch Missing The Search Bar

### ISSUE THREAD

**Issue by guanyu4u** [IdleEndeavor/booksearch#5]
[ravebooksearch.com ](https://ravebooksearch.com/) only shows all the website's elements except for a search bar. I tried this on Chrome, Edge and Firefox with the same result.
![image](https://github.com/IdleEndeavor/booksearch/assets/64021914/079fd215-a5f8-4cfa-b2e8-e7ba372e3db4)

**Comment by guanyu4u** [comment]
Got resloved

**Comment by Oolong22** [comment]
I'm having the same issue. On chrome and on firefox

**Comment by IdleEndeavor** [comment]
I'm am extremely sorry for the inconvenience. 
This tends to occur if the system thinks you are sending too many requests or suspect your requests of being from a bot. It tends to resolve itself after sometime. You do not need to take any other actions.
Once again, sorry for the inconvenience.
